import os

CONFERENCE_PATH = "%s/constants/conferences.csv"
TEAM_PATH = "%s/constants/teams.csv"
SCHEDULE_GENERIC_PATH = "%s/output/%s/schedules/"

OVERTIME_ADJUSTMENT = True

BB_CURRENT_WEEK = 7
BB_HOME_COURT_ADVANTAGE = 3.3
BB_ADJUSTED_RATING_COEFFICIENT = 1.0

FB_CURRENT_WEEK = 16
FB_HOME_FIELD_ADVANTAGE = 3.0
FB_ADJUSTED_RATING_COEFFICIENT = 0.9
